services:
  academy:
    image: postgres:16
    container_name: academy_tania
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
      POSTGRES_DB: academy
    ports:
      - '5436:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: academy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5052:80'
    depends_on:
      - academy
